proto_outdir = "./vendor/proto"

[[dependencies]]
  target = "github.com/Interactions-HSG/uArm-Controller/protobuf"
  branch = "main"
  #revision = "v1.0" # tag doesn't work atm
  revision = "3b2386e93866aa575230fd744c8059cdb57cc27a"
  path = "uarm-controller"

